ports:
  - name: Server-josmar
    port: 80
    onOpen: open-browser

  - name: DB-josmar
    port: 3306
    onOpen: ignore

  - name: Adminer
    port: 8080

tasks:
  - command: |
      sudo docker-compose up
