version: '3.3'
services:
  api:
    container_name: php8.1.9
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/var/www/html/
    ports:
      - 80:80

  josmar_adminer:
    container_name: adminer
    image: adminer:4.8.1
    restart: always
    ports:
      - 8080:8080

  josmar_db:
    container_name: mysql8.0.30
    command: --authentication-policy=mysql_native_password
    restart: always
    build:
      context: ./
      dockerfile: docker/mysql/Dockerfile
    volumes:
      - ./docker/mysql/scripts:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
